Exception occured while processing batch "<%= @batch %>", product "<%= @product_url %>":
<%= @exception.inspect %>
